### ISSUE TITLE
Grafana dashboard not fully loading

### ISSUE THREAD

**Issue by mashidata** [ar51an/unbound-dashboard#10]
Hello,

First of all thank you for this great piece of work. I followed both your guides (unbound-redis and this one) to the letter and managed to install everything without a single error. All services seem to be up and running but some elements in the Grafana dashboard don't load.

Maybe you could point out where the issue might be?

![image](https://github.com/ar51an/unbound-dashboard/assets/165338439/86e5ee08-4f90-4f24-9296-93fd7240efcf)
![image](https://github.com/ar51an/unbound-dashboard/assets/165338439/49863e5c-4c23-459e-bde2-ff3134011cb1)

Thank you very much!

**Comment by ar51an** [comment]
Looks like unbound-exporter is not running.
What is the output of below cmd:

sudo systemctl status prometheus-unbound-exporter

**Comment by mashidata** [comment]
Indeed I went through the whole thing again and one of the services wasnt running. Now it all works just fine. Thank you very much!
