### ISSUE TITLE
Failed to start Prometheus Unbound Exporter

### ISSUE THREAD

**Issue by xaquib666** [ar51an/unbound-dashboard#12]
Hello,

The prometheus unbound exporter service fails to start, and it claims the Start request repeated too quickly. Can you please tell me how to fix it?

Permissions are all correctly set

Thanks!

![image](https://github.com/user-attachments/assets/c1ae6f79-23dc-462c-9a01-b1a9e0b1d9b3)

**Comment by xaquib666** [comment]
Hello,

next step actually shows the probable root cause of the error. GLIBC_2.34 and GLIBC_2.32 are needed.

![image](https://github.com/user-attachments/assets/012e4d2b-9ebd-4f76-b655-1d75e54e559d)

Latest version of bullseyw is installed in this raspberry pi , which only supports 2.31.

![image](https://github.com/user-attachments/assets/6a17fa0a-c587-4bcc-b161-e62d8a0711de)

How did you run unbound-exporter in a raspberrypi?

Thanks!

**Comment by xaquib666** [comment]
Issue fixed after upgarding to debian bookworm!

**Comment by ar51an** [comment]
Glad you figured it out. Current supported OS version is mentioned in the readme under `Specs`:

![image](https://github.com/user-attachments/assets/c0a9f7f5-a2ad-4cef-bbe5-eeac6ce0f7c3)

As a reference you can compile unbound-exporter on non-supportive OS. Compilation is straight forward and the process is explained in the unbound-exporter repo:

https://github.com/ar51an/unbound-exporter
