### ISSUE TITLE
How to use loki, version 3.1.0 (branch: k207, revision: 935aee77) prometheus, version 2.42.0+ds (branch: debian/sid, revision: 2.42.0+ds-5+b5) promtail, version 3.1.0 (branch: k207, revision: 935aee77)

### ISSUE THREAD

**Issue by Potterli20** [ar51an/unbound-dashboard#14]
How to use loki, version 3.1.0 (branch: k207, revision: 935aee77) prometheus, version 2.42.0+ds (branch: debian/sid, revision: 2.42.0+ds-5+b5) promtail, version 3.1.0 (branch: k207, revision: 935aee77)

**Comment by ar51an** [comment]
New release will support the latest version of loki and grafana (most probably over the weekend).

**Comment by ar51an** [comment]
Use Loki's config.yml from unbound-dashboard release v2.3
