### ISSUE TITLE
No unbound-dashboard.json file in project

### ISSUE THREAD

**Issue by Neokamikaze** [ar51an/unbound-dashboard#17]
Hi, 
Thanks for your good job. But i don't find the unbound-dashboard.json in your project.
Could you add this file on  please.
Thx

**Comment by Neokamikaze** [comment]
Ok i understand. i find this file in Grafana. 
Thx for your good job

**Comment by Neokamikaze** [comment]
Sorry, but i don't find the config.yml for loki et promtail in this package. 
Could explain where find these files please.
Thx

**Comment by ar51an** [comment]
Hi,
Everything is mentioned in the installation instructions.

![image](https://github.com/user-attachments/assets/a657e277-e179-4b1c-af79-fd432adb7ba9)

loki's `config.yml` is under `loki dir` and promtail's `config.yml` is under `promtail dir` in the `unbound-dashboard-release-2.3.tar.gz` release.
