### ISSUE TITLE
Threads?

### ISSUE THREAD

**Issue by InstigatorX** [ar51an/unbound-dashboard#3]
Any idea why THREAD count wouldn't be populating? I have it set to 4 in unbound.

**Comment by ar51an** [comment]
Are you using grafana 9.4.*?

**Comment by InstigatorX** [comment]
Yes, just made sure. On Mar 19, 2023, at 6:40 PM, AA ***@***.***> wrote:﻿
Are you using grafana 9.4.*?

**Comment by ar51an** [comment]
Stick with grafana 9.3.8
In grafana 9.4.* you need to edit the panel and update the Threads label under "Organize fields".
There are multiple other issues in grafana 9.4.*. New default font "Inter" looks ugly at places, table overflow scrollbars if footer removed, table headers color removed ...

I will update the dashboard repo once grafana fixes some of the issues.

**Comment by InstigatorX** [comment]
That did the trick. Thx for the tip. Dashboard is great. Thx!
