### ISSUE TITLE
x86?

### ISSUE THREAD

**Issue by mikrologic** [ar51an/unbound-dashboard#5]
Awesome job with this!  Is there any possibility for an x86 tutorial / version?

**Comment by ar51an** [comment]
Check the comment in my reddit post for amd64.
https://www.reddit.com/r/selfhosted/comments/119l044/comment/jb73rjk/?utm_source=share&utm_medium=web2x&context=3

Summarizing it again:
1 - Compile unbound exporter for the required platform. Compilation instructions are available in the exporter repo.
2 - Install grafana, loki and promtail binaries for the required platform.
3 - Rest of the instructions, configs and service should work as it is from this repo.

For grafana, stick with `9.3.*` (latest) version. In the future I will release dashboard updated to grafana `9.5.*`. Check this comment for not releasing grafana `9.4.*` updated dashboard.
https://github.com/ar51an/unbound-dashboard/issues/3#issuecomment-1475429668
