### ISSUE TITLE
word error

### ISSUE THREAD

**Issue by Alyciazsa** [ar51an/unbound-dashboard#7]
![image](https://github.com/ar51an/unbound-dashboard/assets/97645837/3858bd8b-aaed-4c66-9562-d2e494fcc1ba)

**Comment by ar51an** [comment]
Did you edit this panel and try to change the transformation?

**Comment by Alyciazsa** [comment]
No. I didn't edit any.

**Comment by ar51an** [comment]
What is the grafana version you are using?

Edit:
After looking at the font and panel titles alignment in your screenshot, it seems like you are using grafana 9.4.* or later version. 

Stick with grafana 9.3.16
`wget https://dl.grafana.com/oss/release/grafana_9.3.16_arm64.deb`
